### ISSUE TITLE
Legend generation fails on multiple symbolizers or OL style function

### ISSUE THREAD

**Issue by raitisbe** [geostyler/geostyler-legend#285]
# Bug

**Describe the bug**
The problem stems from `renderer.setStyle(styleItem);` line, where `setStyle` only accepts an OlStyle object, not an array or function. In that case `catch` block is executed, the promise is rejected and no legend is generated.

**To Reproduce**
1. Go to https://geostyler.github.io/geostyler-demo/
2. Add an additional Icon symbolizer to the existing Mark symbolizer
3. Expand Legend tab
4. Set some attribute for Mark symbolizer, radius for example, so the icon gets regenerated: 
![image](https://user-images.githubusercontent.com/395514/135279689-e337c87c-87e4-459e-989a-8219c43f66df.png)

5. See error in console and empty legend graphics on the right side:
![image](https://user-images.githubusercontent.com/395514/135279609-b80c872e-cbce-4b35-ae9c-5c38b8ed3d92.png)

**Expected behavior**
getRuleIcon function should return an icon by combining the multiple OlStyles and generating a composite icon such as:
![image](https://user-images.githubusercontent.com/395514/135280045-60521122-b766-43dc-bbca-b7c2b3bc839f.png)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Not relevant
 - Browser Chrome
 - Version Not relevant

**Comment by KaiVolland** [comment]
Thanks for the report. I'll have a look at it.
