### ISSUE TITLE
Problem importing LegendRenderer 

### ISSUE THREAD

**Issue by ThierryNormand** [geostyler/geostyler-legend#443]
**Describe the bug**
When importing the library for an Angular project, I get the error __WEBPACK_IMPORTED_MODULE_ is not a constructor. To solve this problem, I used the following syntax which worked for a similar problem with OlStyleParser:
`import { LegendRenderer as MyLegendRenderer } from 'geostyler-legend/dist/LegendRenderer/LegendRenderer';
`
However, I get the error : 
`Module '"geostyler-legend/dist/LegendRenderer/LegendRenderer"' has no exported member 'LegendRenderer'.
`

**Expected behavior**
I should not receive an error for the import.

**Version**
 - Angular: 16.2.5
 - geostyler-legend: 4.0.0

**Additional context**
I found that the declaration of LegendRenderer class has no "export" like OlStyleParser. Adding 
`**export** declare class LegendRenderer{...}` solves the problem.

**Comment by rdewit** [comment]
I have the following in my project (also with geostyler-legend v4.0.0 but vite/React and without Angular), which works fine for me:

`import GeostylerLegendRenderer from 'geostyler-legend/dist/LegendRenderer/LegendRenderer'`

Just making sure that you have tried using the default export? If so, how did you originally try to import LegendRenderer that gave you the error _ _WEBPACK_IMPORTED_MODULE is not a constructor_?

**Comment by ThierryNormand** [comment]
I tried using the default export, which gave the WEBPACK error. Trying to solve the error as I have done with Geostyler gave me the error stated in my post. As noted in my initial post, I think the LegendRenderer class is missing an export statement.

**Comment by pelord** [comment]
Any updates?

**Comment by hwbllmnn** [comment]
I added a named export in #444

**Comment by hwbllmnn** [comment]
The fix is contained in `4.0.1`
